fix: use up to date pricing data
deepgenomics/cromwell-monitor pull request #14
Opened 2024-09-16 21:00 UTC by SophiaPerzan-DG

also:
    feat: add GPU cost to runtime cost estimate metric
    feat: use gcp pricing api v1 for pricing

Fixes INF-479

2024-09-16 21:03 UTC, SophiaPerzan-DG commented on tests/data/services_pricelist.json
Using new pricelist from google pricing api

2024-09-16 21:05 UTC, SophiaPerzan-DG commented on tests/data/legacy_pricelist.json
deleted old pricelist since its no longer used

2024-09-16 21:09 UTC, SophiaPerzan-DG commented on tests/test_monitor.py
> +    assert actual > 0
Went back and worth about whether or not to test for a specific price but decided not to because if the pricelist gets updated it will break tests. Also, if the returned value is an int, the only thing thats left to check anyway is that the pricing math is being done correctly which is pretty trivial. You'd essentially just be asserting the same math statement twice in the actual function, and the test function. Seemed weird to me to test that.

2024-09-16 21:10 UTC, SophiaPerzan-DG commented on tests/data/pricelist.json
out of date pricing data

2024-09-18 20:43 UTC, ovesh requested changes

2024-09-18 20:43 UTC, ovesh commented on gcp_monitor.py
> +            case "nvidia-tesla-t4":
should be a "const" dict

2024-09-18 20:43 UTC, ovesh commented on gcp_monitor.py
> +        match disk["type"]:
dict

2024-09-18 20:43 UTC, ovesh commented on monitor.py
> +    Returns the access token as a string
Personally I think this kind of documentation is excessive. Maybe just link to the relevant docs.

2024-09-18 20:43 UTC, ovesh commented on monitor.py
> +    requests.exceptions.RequestException
*If* we are going to do this, maybe we should adhere to the Sphinx docstring format.
https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html

2024-09-18 20:43 UTC, ovesh commented on monitor.py
> +            "https://cloudbilling.googleapis.com/v1/services/6F81-5844-456A/skus",
comment on where you got `6F81-5844-456A` from

2024-09-18 20:43 UTC, ovesh commented on tests/data/services_pricelist.json
Can we make the file small if it's only used for tests?

2024-09-18 20:43 UTC, ovesh commented on tests/test_monitor.py
> +    assert actual > 0
The pricelist is committed to the repo, why would it get updated?
I think it's worthwhile to test the price calculation, if only for documenting how it works.

2024-10-10 16:41 UTC, SophiaPerzan-DG commented on gcp_monitor.py
> +    gpu_type = gpu_type.split("/")[-1] if gpu_type else None
Discussed offline, the internal metadata is likely more robust in terms of getting the resources mounted to the VM, and given that pynvml still isn't working in the monitoring container anyway, using the internal metadata endpoint is fine.

2024-10-10 17:54 UTC, ovesh commented on gcp_monitor.py
> +    gpu_type = gpu_type.split("/")[-1] if gpu_type else None
Please leave a comment on the code as well.

2024-10-31 17:26 UTC, ovesh commented on tests/data/test_get_disk_hour_pricelist.json
Is this really the smallest we can make this file? (and similarly others)

2024-10-31 17:26 UTC, ovesh commented on monitor.py
> +        logging.error(f"Error using pricing data for metrics: {e}")
I think we're double logging here (consider removing some of the log statements from gcp_monitor.py, replacing them with wrapped exceptions)

2024-10-31 17:34 UTC, ovesh commented on tests/test_monitor.py
> +    sku = [sku for sku in pricelist if sku_id in sku["skuId"]][0]
more pythonic (and performant)
```suggestion
    sku = next(sku for sku in pricelist if sku_id in sku["skuId"])
```

2024-11-04 21:20 UTC, SophiaPerzan-DG commented on gcp_monitor.py
> +        "gpu_type": gpu_type,
Went over all usages and returning None doesnt cause a problem. Created a techdebt ticket to address the root cause (giant dict) in the future

2024-11-05 17:16 UTC, SophiaPerzan-DG commented on monitor.py
> +        logging.error(f"Error using pricing data for metrics: {e}")
removed the unnecessary logs and redundant re-raises

2024-11-05 17:17 UTC, SophiaPerzan-DG commented on gcp_monitor.py
> +        raise ValueError("Could not determine number of CPUs")
it is caught

2024-11-05 17:17 UTC, SophiaPerzan-DG commented on gcp_monitor.py
> +    # Units are whole dollars, nanos are cents but represented as nanos of a dollar
Reworded this comment and changed the func

2024-11-05 17:21 UTC, ovesh approved these changes

2024-11-05 19:01 UTC, merged